language: node_js
node_js:
  - "8.9.4"
before_install:
  - npm install
script:
 - npm test
after_success: 
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < client/coverage/lcov.info
  - npm run coverage
